apiVersion: v1
kind: Service
metadata:
  name: "hello-world"
spec:
  selector:
    app: helloworld
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    {{- if .Values.fixed_nodeport }}
      nodePort: 30123
    {{- end }}
